export const COLORES = [
    "único",
    "rojo",
    "rojo claro",
    "rojo oscuro",
    "azul",
    "azul claro",
    "azul oscuro",
    "verde",
    "verde claro",
    "verde oscuro",
    "negro",
    "blanco",
    "gris",
    "gris claro",
    "gris oscuro",
    "amarillo",
    "amarillo claro",
    "amarillo oscuro",
    "naranja",
    "naranja claro",
    "naranja oscuro",
    "morado",
    "morado claro",
    "morado oscuro",
    "rosado",
    "rosado claro",
    "rosado oscuro",
    "café",
    "café claro",
    "café oscuro",
    "beige",
    "dorado",
    "plateado",
    "vino tinto",
    "verde azul",
    "fucsia",
    "marfil",
    "transparente",
    "multicolor"
];